name = cushions
title = bc_cushions
description = adds cushions,inspirated by original mod by krabNchous with Whoopsy Cushions
author = wrxxnch
depends = mcl_dyes,mcl_achievements, mcl_core, mcl_lush_caves, mcl_campfires
license = GNU General Public License, version 2