title = Natural Habitat
name = natural_habitat
author = Mish7913
description = Modify Minetest Game and MineClonia Game.
depends = 
optional_depends = default, flowers, mcl_init, mcl_core, mcl_structures, mcl_deepslate, mcl_sounds, mcl_mushrooms, mcl_lush_caves, mcl_pale_oak, mcl_nether, schemedit