name = postick
description = Ferramenta PosTick para selecionar posições (tipo WorldEdit light), com seleção no ar usando AUX1 e cópia automática para a área de transferência.
author = Jean Pierre




