name = armor_stand_arms
title = Armor Stand with Arms
author = nandologia
description = Adds an armor stand with arms that displays armor, holds a weapon in one hand and a shield in the other. Works with Mineclonia, VoxeLibre, and Minetest Game (with the 3d_armor modpack).
optional_depends = mcl_armor, mcl_armor_stand, mcl_core, mcl_sounds, mcl_stairs, default, stairs, 3d_armor, 3d_armor_stand, shields, screwdriver
supported_games = mineclonia, mineclone2, minetest_game
